const demoSamplePayload = {
  video_id: "hackathon-product-demo",
  title: "Opportunity Radar Hackathon Product Demo",
  generated_at: "2026-03-28T16:20:00+05:30",
  fps: 30,
  width: 1920,
  height: 1080,
  duration_in_frames: 5400,
  duration_seconds: 180,
  brand: {
    name: "Opportunity Radar",
    tagline: "AI for the Indian Investor",
  },
  tabs: [
    { key: "video_engine", label: "Video Engine" },
    { key: "opportunity_radar", label: "Opportunity Radar" },
    { key: "chart_intelligence", label: "Chart Intelligence" },
    { key: "market_chatgpt", label: "Market ChatGPT" },
  ],
  source_runs: {
    disclosure_run_label: "2026-03-28",
    chart_run_label: "2026-03-28T14-02-33+05-30",
  },
  audio: {
    enabled: true,
    available: false,
    provider: "openai",
    model: "gpt-4o-mini-tts",
    voice: "ash",
    speed: 0.92,
    ai_generated: true,
    disclosure: "Narration uses an AI-generated voice.",
  },
  sections: [
    {
      id: "intro",
      type: "hero",
      active_tab: "video_engine",
      duration_frames: 450,
      eyebrow: "Hackathon Demo",
      title: "One intelligence layer across four market products.",
      body: "This walkthrough shows how Opportunity Radar turns ET-style data into signal-finding, chart scanning, grounded chat, and auto-generated market video.",
      stats: [
        { label: "Products", value: "4" },
        { label: "Disclosure alerts", value: 5 },
        { label: "Chart alerts", value: 743 },
        { label: "Video", value: "1080p" },
      ],
      voiceover: "Opportunity Radar turns one market intelligence layer into four investor-facing products. In this walkthrough, we move from signal discovery to chart structure, then to grounded chat, and finally to auto-generated market video, all built from the same live system.",
    },
    {
      id: "overview",
      type: "overview",
      active_tab: "video_engine",
      duration_frames: 450,
      eyebrow: "Product Surface",
      title: "The app is organized around the exact hackathon brief.",
      body: "Each tab is a product surface with its own job, user, and output format.",
      cards: [
        {
          label: "Opportunity Radar",
          tone: "bullish",
          headline: "Signal-finder for filings and regulatory shifts",
          detail: "Continuously monitors disclosures, quarterly results, insider trades, commentary shifts, and block or bulk deals.",
        },
        {
          label: "Chart Intelligence",
          tone: "neutral",
          headline: "Breakouts, reversals, levels, and divergences",
          detail: "Scans the full NSE universe and attaches stock-specific back-tested context to each published setup.",
        },
        {
          label: "Market ChatGPT",
          tone: "neutral",
          headline: "Grounded chat over indexed runs",
          detail: "Answers from retrieved sources, signal bundles, and indexed evidence instead of guessing from priors.",
        },
        {
          label: "Video Engine",
          tone: "bullish",
          headline: "Zero-human-editing market walkthroughs",
          detail: "Turns the latest data into a narrated 1080p product film and a daily market wrap.",
        },
      ],
      voiceover: "Each tab has a distinct job, but all four read from the same market context. That lets an investor move from a fresh filing, to chart confirmation, to a cited explanation, and then to a visual briefing without losing continuity.",
    },
    {
      id: "opportunity",
      type: "showcase",
      active_tab: "opportunity_radar",
      duration_frames: 750,
      eyebrow: "Opportunity Radar",
      title: "Missed opportunities are surfaced as daily investor-facing alerts.",
      body: "The disclosure lane watches filings, insider activity, bulk and block deals, quarterly results, commentary shifts, and regulatory changes, then filters them into a high-signal board.",
      stats: [
        { label: "Run", value: "2026-03-28" },
        { label: "Fresh events", value: 34 },
        { label: "Published alerts", value: 5 },
        { label: "AI briefs", value: 5 },
      ],
      cards: [
        {
          symbol: "LT",
          company: "Larsen & Toubro Limited",
          direction: "bullish",
          headline: "New orders boost growth outlook",
          summary: "Larsen & Toubro's official disclosure of new orders suggests strong business momentum and potential revenue growth.",
          metric_label: "Score",
          metric_value: 26,
        },
        {
          symbol: "SEAMECLTD",
          company: "Seamec Limited",
          direction: "bullish",
          headline: "New Order Announcement",
          summary: "Fresh orders could strengthen revenue visibility and keep the name in the research queue.",
          metric_label: "Score",
          metric_value: 26,
        },
        {
          symbol: "ESTER",
          company: "Ester Industries Limited",
          direction: "bearish",
          headline: "Potential closure disclosure",
          summary: "A corporate filing raises risk around operations and makes the name a defensive watchlist candidate.",
          metric_label: "Score",
          metric_value: 28,
        },
      ],
      voiceover: "Opportunity Radar is the filing-led signal finder. It continuously watches disclosures, quarterly results, insider trades, bulk and block deals, commentary shifts, and regulatory changes. The goal is not to summarize noise, but to surface the few updates that deserve immediate research.",
    },
    {
      id: "agentic",
      type: "workflow",
      active_tab: "opportunity_radar",
      duration_frames: 720,
      eyebrow: "Agentic Layer",
      title: "Signals go through a multi-agent research desk before they are published.",
      body: "For the demo, LT is passed through a filing analyst, a bull analyst, a bear analyst, and a referee.",
      steps: [
        { step: "Scout", detail: "Collects the daily market universe from disclosures and related feeds." },
        { step: "Router", detail: "Shortlists the highest-signal names for deeper review." },
        { step: "Debate Desk", detail: "Filing Analyst, Bull Analyst, and Bear Analyst each build a separate view." },
        { step: "Referee", detail: "Weights evidence over hype and publishes the final investor-facing verdict." },
      ],
      cards: [
        {
          label: "Filing Analyst",
          tone: "neutral",
          headline: "Builds a structured evidence brief from filings and attachments.",
          detail: "Reads the what-changed facts before any market opinion is formed.",
        },
        {
          label: "Bull Analyst",
          tone: "bullish",
          headline: "Frames the strongest supported upside case.",
          detail: "Shows where the filing could translate into revenue or sentiment improvement.",
        },
        {
          label: "Bear Analyst",
          tone: "bearish",
          headline: "Stress-tests the signal with the strongest risk case.",
          detail: "Looks for missing detail, execution risk, or weak follow-through.",
        },
        {
          label: "Referee",
          tone: "bullish",
          headline: "Produces the final investor-facing verdict.",
          detail: "Turns the debate into a publishable signal label, summary, and confidence score.",
        },
      ],
      voiceover: "Once a name is shortlisted, the agentic layer takes over. A scout gathers the universe, a router prioritizes the strongest candidates, a filing analyst explains what changed, bull and bear analysts test the thesis from both sides, and a referee publishes the final investor-facing verdict.",
    },
    {
      id: "chart",
      type: "showcase",
      active_tab: "chart_intelligence",
      duration_frames: 750,
      eyebrow: "Chart Pattern Intelligence",
      title: "Real-time technical pattern detection stays in its own dedicated lane.",
      body: "The chart engine scans the full NSE universe for breakouts, reversals, support and resistance reactions, and divergences, then attaches stock-specific back-tested success rates.",
      stats: [
        { label: "Chart run", value: "2026-03-28T14-02-33+05-30" },
        { label: "Universe", value: 2122 },
        { label: "Published", value: 743 },
        { label: "Backtest horizon", value: "7D" },
      ],
      cards: [
        {
          symbol: "GRAPHITE",
          company: "Graphite India Limited",
          direction: "bullish",
          headline: "Bullish Breakout",
          summary: "Price cleared resistance with volume, but the prior hit rate has been mixed.",
          metric_label: "7D hit rate",
          metric_value: "35.7%",
          detail: "1d | 14 samples",
        },
        {
          symbol: "SGMART",
          company: "SG Mart Limited",
          direction: "bullish",
          headline: "Bullish Breakout",
          summary: "Fresh strength arrived above resistance, though stock-specific history is still thin.",
          metric_label: "7D hit rate",
          metric_value: "50.0%",
          detail: "1d | 4 samples",
        },
        {
          symbol: "DDEVPLSTIK",
          company: "Ddev Plastiks Industries Limited",
          direction: "bearish",
          headline: "Bearish Breakdown",
          summary: "The stock broke below support with volume and now leads the defensive side of the board.",
          metric_label: "7D hit rate",
          metric_value: "0.0%",
          detail: "1d | 3 samples",
        },
      ],
      voiceover: "Chart Pattern Intelligence runs in parallel to the filing lane. It scans the NSE universe for breakouts, reversals, support and resistance reactions, and divergences. Every setup includes key levels plus stock-specific back-tested context, so the chart feed stays interpretable instead of becoming just another screener.",
    },
    {
      id: "chat",
      type: "chat",
      active_tab: "market_chatgpt",
      duration_frames: 720,
      eyebrow: "Market ChatGPT",
      title: "Grounded answers are generated from indexed runs and retrieved evidence.",
      body: "This lane is designed to beat shallow market chat by staying source-cited and run-aware.",
      prompt: "Why is LT interesting today, and what should I watch next?",
      answer: "LT stands out because the disclosure lane surfaced a meaningful order-related update in the latest run. On top of that, the system keeps the stock in the research queue because order inflow can change forward sentiment quickly. The next step is to verify the size of the order, execution timeline, and whether follow-through confirms the thesis.",
      sources: [
        { label: "Disclosure run", value: "2026-03-28" },
        { label: "Primary symbol", value: "LT" },
        { label: "Chart context", value: "Latest chart setup available" },
      ],
      stats: [
        { label: "Indexed docs", value: 34 },
        { label: "Retrieved chunks", value: 88 },
        { label: "Chat state", value: "Ready" },
      ],
      voiceover: "Market ChatGPT is built for grounded analysis, not generic market chatter. It retrieves evidence from indexed runs before answering, so the response can explain why a stock matters, what changed in the latest run, and what an investor should verify next with sources attached.",
    },
    {
      id: "video",
      type: "showcase",
      active_tab: "video_engine",
      duration_frames: 750,
      eyebrow: "AI Market Video Engine",
      title: "The same intelligence layer can publish itself as a narrated 1080p market film.",
      body: "The video engine converts live radar counts, chart breadth, directional balance, and queue logic into a product-quality MP4 with no manual editing.",
      stats: [
        { label: "Render state", value: "synced" },
        { label: "Quality", value: "1080p" },
        { label: "Duration", value: "42s" },
        { label: "Narration", value: "ash" },
      ],
      cards: [
        {
          symbol: "Wrap",
          company: "Daily market film",
          direction: "bullish",
          headline: "Daily market wrap",
          summary: "The film is assembled from disclosure alerts, chart alerts, overlap names, directional balance, and a merged research queue.",
          metric_label: "Media URL",
          metric_value: "/api/video/media/latest",
        },
        {
          symbol: "Matrix",
          company: "Generation logic",
          direction: "neutral",
          headline: "The film is data-driven, not manually edited.",
          summary: "Counts, scores, breadth, tone, and queue logic all shape the scenes and narration automatically.",
          metric_label: "Voice",
          metric_value: "ash",
        },
      ],
      voiceover: "The Video Engine is a publishing layer on top of the research system. It turns live signal counts, chart breadth, directional balance, and the carry-forward queue into a watchable market briefing. The output is automatic, but the story still comes directly from the underlying data.",
    },
    {
      id: "command",
      type: "command",
      active_tab: "video_engine",
      duration_frames: 540,
      eyebrow: "Demo Ops",
      title: "The whole demo can be refreshed with one command before presenting.",
      body: "Instead of running separate prep steps, the app now ships with a single command that refreshes data, chart scans, and the market video.",
      command: "python scripts/prepare_demo.py --serve",
      checks: [
        "refresh Opportunity Radar",
        "refresh Chart Pattern Intelligence",
        "render the latest market video",
        "start the local demo server",
      ],
      voiceover: "Because all four products share one pipeline, the platform can refresh quickly when new market data arrives. A single refresh updates filings, chart patterns, chat context, and the generated video, so the investor sees one consistent market picture instead of four disconnected tools.",
    },
    {
      id: "close",
      type: "close",
      active_tab: "video_engine",
      duration_frames: 270,
      eyebrow: "Submission Close",
      title: "One data layer. Four product surfaces. Demo-ready today.",
      body: "The architecture keeps deterministic market logic where precision matters and agentic reasoning where judgment matters.",
      bullets: [
        "Opportunity Radar: signal-finder for filings",
        "Chart Pattern Intelligence: technical setups with backtests",
        "Market ChatGPT: grounded, cited answers",
        "AI Market Video Engine: narrated visual briefings",
      ],
      voiceover: "The result is a market intelligence stack with four clear outputs: signals, chart setups, grounded answers, and video briefings. That combination is what makes Opportunity Radar useful for discovery, validation, and communication in one system.",
    },
  ],
};

demoSamplePayload.narration = demoSamplePayload.sections.map((section) => ({
  scene_id: section.id,
  text: section.voiceover,
}));

demoSamplePayload.tts_script = demoSamplePayload.sections
  .map((section) => section.voiceover)
  .filter(Boolean)
  .join(" ");

export default demoSamplePayload;
